# Generated by Django 5.1.3 on 2024-11-15 22:05

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default=None, max_length=250, unique=True, validators=[subject_app.validators.validate_subject_format])),
                ('professor', models.CharField(default='Mr. Cahan', max_length=250, validators=[subject_app.validators.validate_professor_name])),
            ],
        ),
    ]
