# Generated by Django 5.1.3 on 2024-12-02 19:22

import django.core.validators
import exercise_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_of_reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField()),
                ('exercise_name', models.CharField(validators=[exercise_app.validators.validate_exercise_name])),
            ],
        ),
    ]
