# Generated by Django 5.1.3 on 2024-12-05 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_initial'),
        ('workout_app', '0002_workout_workout_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='num_of_reps',
            new_name='actual_num_of_reps',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='num_of_sets',
            new_name='actual_num_of_sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_num_of_reps',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='goal_num_of_sets',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_id', to='workout_app.workout'),
        ),
    ]
