# Generated by Django 5.1.3 on 2024-12-05 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0004_rename_workout_exercise_workout_id'),
        ('workout_app', '0004_alter_workout_tracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(2000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workout_app.workout'),
        ),
    ]
