# Generated by Django 5.1.3 on 2024-12-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0005_exercise_weight_alter_exercise_workout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='iteration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
