# Generated by Django 5.1.3 on 2024-12-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0006_exercise_iteration'),
        ('workout_app', '0004_alter_workout_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_app.workout'),
        ),
    ]
