# Generated by Django 5.1.3 on 2024-12-12 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0007_alter_exercise_workout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
