# Generated by Django 5.1.3 on 2024-12-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0008_exercise_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='actual_num_of_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='actual_num_of_sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='goal_num_of_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='goal_num_of_sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
    ]
