# Generated by Django 5.1.3 on 2024-11-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0003_initial'),
        ('to_do_app', '0005_remove_task_parent_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_app.list'),
        ),
    ]
