# Generated by Django 5.1.3 on 2024-12-13 18:03

import chart_data_app.validators
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_app', '0009_remove_exercise_actual_num_of_reps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.PositiveIntegerField()),
                ('actual_num_of_sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_num_of_reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(validators=[chart_data_app.validators.validate_valid_type])),
                ('goal_num_of_sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('goal_num_of_reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)])),
                ('date', models.DateField(default=datetime.date.today)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='exercise_app.exercise')),
            ],
        ),
    ]
