# Generated by Django 5.1.3 on 2024-12-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartdata',
            old_name='workout_id',
            new_name='exercise_id',
        ),
    ]
