# Generated by Django 5.1.3 on 2024-12-13 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data_app', '0002_rename_workout_id_chartdata_exercise_id'),
        ('exercise_app', '0009_remove_exercise_actual_num_of_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='exercise_app.exercise'),
        ),
    ]
