# Generated by Django 5.1.3 on 2024-12-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data_app', '0003_alter_chartdata_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='date',
        ),
    ]
