# Generated by Django 5.1.3 on 2024-12-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data_app', '0006_chartdata_exercise_iteration'),
        ('exercise_app', '0009_remove_exercise_actual_num_of_reps_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartdata',
            name='exercise_iteration',
        ),
        migrations.AddConstraint(
            model_name='chartdata',
            constraint=models.UniqueConstraint(fields=('exercise_id', 'iteration'), name='exercise_iteration'),
        ),
    ]
