# Generated by Django 5.1.3 on 2024-12-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data_app', '0007_remove_chartdata_exercise_iteration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='iteration',
        ),
    ]
