# Generated by Django 5.1.3 on 2024-12-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_data_app', '0008_remove_chartdata_iteration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartdata',
            name='exercise_iteration',
        ),
    ]
