# Generated by Django 5.1.3 on 2024-12-02 21:39

import workout_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(default='Untitled_Workout', validators=[workout_app.validators.validate_workout_name]),
        ),
    ]
