# Generated by Django 5.1.3 on 2024-12-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_tracker_user_id'),
        ('workout_app', '0002_workout_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='tracker_name',
        ),
        migrations.AddField(
            model_name='workout',
            name='tracker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_id', to='tracker_app.tracker'),
            preserve_default=False,
        ),
    ]
