# Generated by Django 5.1.3 on 2024-12-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_alter_tracker_user_id'),
        ('workout_app', '0003_remove_workout_tracker_name_workout_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='tracker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='tracker_app.tracker'),
        ),
    ]
