# Generated by Django 5.1.3 on 2024-12-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_rename_user_id_tracker_user'),
        ('workout_app', '0005_alter_workout_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='tracker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='tracker_app.tracker'),
        ),
    ]
