# Generated by Django 5.1.3 on 2024-11-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
