# Generated by Django 5.1.3 on 2024-12-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_alter_tracker_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='user_id',
            new_name='user',
        ),
    ]
