# Generated by Django 5.1.3 on 2024-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='good_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lock_combination',
            field=models.CharField(default='XX-XX-XX', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='lock_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='example@school.com', max_length=255),
        ),
    ]
