# Generated by Django 5.1.3 on 2024-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_student_good_student_student_lock_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=255),
        ),
    ]
