# Generated by Django 5.1.3 on 2024-11-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_student_lock_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lock_combination',
            new_name='locker_combination',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lock_number',
            new_name='locker_number',
        ),
    ]
