# Generated by Django 5.1.3 on 2024-11-14 19:27

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_alter_student_locker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=50, validators=[student_app.validators.validate_combination_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=255, validators=[student_app.validators.validate_name_format]),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(default=None, max_length=255, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default=None, max_length=255, unique=True, validators=[student_app.validators.validate_school_email]),
        ),
    ]
